title: Noteworthy Articles 
email: 
description: >- 
  Articles that I find interesting enough to keep around. I am frequently
  asked how somebody in my position keeps up with trends on leadership and
  Software Craftsmanship. 

baseurl: "/axe-sharpening" 
url: "https://wrobbins.github.io"

github_username: wrobbins 

# Build settings
markdown: kramdown
remote_theme: wrobbins/mostly-text
plugins:
  - jekyll-feed
  - jekyll-remote-theme

